[package]
name = "advent_of_code_2017_rs"
version = "0.1.0"
authors = ["Matthias Krüger <matthias.krueger@famsik.de>"]

[[bin]]
name = "01_1"
[[bin]]
name = "01_2"


[[bin]]
name = "02_1"




[dependencies]
